CatchClauseSignature has broken operation
It looks like the getParameterName() operation on org.aspectj.lang.reflect.
CatchClauseSignature is not working.
Instead of returning the name of the exception as declared in the matched handler, returns the string value "<missing>".
Here is a test case that shows the problem :- 
------START OF TEST CASE CODE----------- public class MyApp { public void doSomething() { // Get around "unreachable code error...
if (true) { throw new BusinessException("Surprise!!"); } System.out.println("Busy doing 